# Generated by Django 4.2.2 on 2023-06-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('adress', models.CharField(max_length=255)),
                ('project_sum', models.FloatField()),
                ('status', models.CharField(choices=[('BOSHLANMAGAN', 'Boshlanmagan'), ('ARAFASIDA', 'Yopilish arafasida'), ('TOLANDI', "To'landi")], default='BOSHLANMAGAN', max_length=15)),
                ('customer_inn', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('json_body', models.JSONField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id', to='tasks.task')),
            ],
        ),
    ]
