# Generated by Django 4.2.2 on 2023-06-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_project_left_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='task_id',
            new_name='task',
        ),
    ]
